### ISSUE TITLE
The TODO List

### ISSUE THREAD

**Issue by Rhilip** [Rhilip/Byrbt-Autoseed#4]
- [ ] Automatically generated Screenshot time
- [ ] Fix Get Mediainfo Error when group is fleet
- [ ] use UPsert instead when update torrent's list to database

**Comment by Rhilip** [comment]
# TV Series
**Last Update In This Page: 20170522**
## Scene-HDTV-720p
- 2 Broke Girls
- 24 Legacy
- 12 Monkeys
- American Horror Story
- Arrow
- APB
- American Gods
- Better Call Saul
- Billions
- Black Mirror
- Black Sails
- Bates Motel
- Blindspot
- Crazy Ex-Girlfriend
- Criminal Minds
- Colony
- Criminal Minds Beyond Borders
- DCs Legends of Tomorrow
- Designated Survivor
- Elementary
- Fargo
- Fear The Walking Dead
- Frequency
- Grimm
- Gotham
- Greys Anatomy
- Genius
- Hawaii Five-0
- Harlots
- High Maintenance
- Homeland
- How to Get Away with Murder
- iZombie
- Inside No 9
- Into the Badlands
- Jane the Virgin
- Lethal Weapon
- Legion
- Lucifer
- Making History
- Marvels Agents of S H I E L D
- Madam Secretary
- Masters of Sex
- Modern Family
- Mom
- Mr Robot
- New Girl
- Orphan Black
- Quantico
- Scorpion
- Shameless US
- South Park
- Supernatural
- Suits
- Supergirl
- Scandal US
- Silicon Valley
- Prison Break
- Taken
- Teen Wolf
- Twin Peaks
- Timeless
- The Americans 2013
- The 100
- The Blacklist
- The Blacklist Redemption
- The Expanse
- The Exorcist
- The Flash 2014
- The Last Man on Earth
- The Magicians
- The Originals
- The Strain
- The Vampire Diaries
- The Walking Dead
- This Is Us
- Vikings
- Veep
- Westworld
- Z Nation

## Scene-HDTV-720p.1080p
- The Big Bang Theory

## Scene-Webrip-720p
- The Good Fight
- American Gods
