### ISSUE TITLE
The TODO list

### ISSUE THREAD

**Issue by Rhilip** [Rhilip/Byrbt-Autoseed#5]
- [ ] Automatically generated Screenshot time
- [x] Fix Get Mediainfo Error when group is fleet
- [x] use UPsert instead when update torrent's list to database
- [ ] Add a web dome to show Autoseed's status( may use Flask or web.py)

**Comment by Rhilip** [comment]
Done `Fix Get Mediainfo Error when group is fleet`
In commit https://github.com/Rhilip/Pt-Autoseed/commit/70e038f603aa249e278ef8ddd1ec5aa165dafd20  -> https://github.com/Rhilip/Pt-Autoseed/commit/44e47595126c20d05b358d54bb5fc3ea06c6091b

**Comment by Lengsir** [comment]
能不能添加知行PT的支持？
